//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orianna_v2._0.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orianna_v2._0.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BanBrasil {
            get {
                object obj = ResourceManager.GetObject("BanBrasil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BanUsa {
            get {
                object obj = ResourceManager.GetObject("BanUsa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Icon semelhante a (Ícone).
        /// </summary>
        public static System.Drawing.Icon brain_icon {
            get {
                object obj = ResourceManager.GetObject("brain_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap default_perfil {
            get {
                object obj = ResourceManager.GetObject("default_perfil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap export {
            get {
                object obj = ResourceManager.GetObject("export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap happy {
            get {
                object obj = ResourceManager.GetObject("happy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap import {
            get {
                object obj = ResourceManager.GetObject("import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap import1 {
            get {
                object obj = ResourceManager.GetObject("import1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mic {
            get {
                object obj = ResourceManager.GetObject("mic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap normal {
            get {
                object obj = ResourceManager.GetObject("normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a orianna;
        ///yes;
        ///no;
        ///what time is it;
        ///what day is it;
        ///thank you;
        ///current temperature;
        ///report;
        ///shut down system;
        ///shut down computer;
        ///nothing;
        ///silent;
        ///shut down computer;
        ///excuse me;
        ///minimize;
        ///what are you for;
        ///shut up	 
        ///how are you;
        ///help;
        ///send email from emergency;
        ///restart computer;
        ///restart system;
        ///good morning;
        ///good afternoon;
        ///good night;
        ///sorry;
        ///hi;
        ///hello;
        ///sleep mode;
        ///open news;
        ///stop;
        ///forward;
        ///backward;
        ///turn left;
        ///turn right;.
        /// </summary>
        public static string reco_enUS {
            get {
                return ResourceManager.GetString("reco_enUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a orianna;
        ///sim;
        ///não;
        ///que horas são;
        ///que dia é hoje;
        ///obrigado;
        ///temperatura atual;
        ///relatorio;
        ///desligar sistema;
        ///desligar computador;
        ///nada;
        ///silencio;
        ///desligar computador;
        ///licença;
        ///minimize;
        ///para que você serve;
        ///cala boca;
        ///tudo bem;
        ///socorro;
        ///enviar email de emergência;
        ///reiniciar computador;
        ///reiniciar sistema;
        ///bom dia;
        ///boa tarde;
        ///boa noite;
        ///desculpa;
        ///oi;
        ///olá;
        ///modo repouso;
        ///abrir noticia;
        ///parar;
        ///para frente;
        ///para trás;
        ///girar para esquerda;
        ///girar para direita;.
        /// </summary>
        public static string reco_ptBR {
            get {
                return ResourceManager.GetString("reco_ptBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap sad {
            get {
                object obj = ResourceManager.GetObject("sad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap sleep {
            get {
                object obj = ResourceManager.GetObject("sleep", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Damaged speech recognition module;
        ///hello welcome back;
        ///Your data has been successfully loaded.;
        ///Say it;
        ///Yea;
        ///I&apos;m here;
        ///Speak;
        ///stopping;
        ///turning left;
        ///turning right;
        ///Good Morning;
        ///Do you want to hear the report?;
        ///Good afternoon;
        ///good night;
        ///how can I help you?;
        ///Hi;
        ///everything is fine with you?;
        ///you are welcome;
        ///Now are;
        ///today is;
        ///the current temperature of;
        ///It&apos;s;
        ///degrees Celsius;
        ///do you really want to shut down the system?;
        ///do you really want to restart the system?;
        ///do you really wan [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string speech_enUS {
            get {
                return ResourceManager.GetString("speech_enUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Módulo de reconhecimento de voz danificado;
        ///Olá bem vindo de volta;
        ///Seus dados foram carrregados com sucesso.;
        ///Diga;
        ///Sim;
        ///Estou aqui;
        ///Fale;
        ///parando;
        ///girando para esquerda;
        ///girando para direita;
        ///bom dia;
        ///deseja ouvir o relatório?;
        ///boa tarde;
        ///boa noite;
        ///como posso te ajudar?;
        ///olá;
        ///está tudo bem com você?;
        ///de nada;
        ///Agora são;
        ///hoje é;
        ///a temperatura atual de;
        ///é;
        ///graus celsius;
        ///você realmente deseja desligar o sistema?;
        ///você realmente deseja reiniciar o sistema?;
        ///você realmente deseja rei [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string speech_ptBR {
            get {
                return ResourceManager.GetString("speech_ptBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap usb {
            get {
                object obj = ResourceManager.GetObject("usb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
